# Generated by Django 4.2.3 on 2023-07-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero',
            field=models.PositiveIntegerField(),
        ),
    ]
